### ISSUE TITLE
请问release到相对目录具体是做什么？

### ISSUE THREAD

**Issue by Julienedies** [xwenliang/fis-zoo#1]
我在做一个基于ionic的hybrid app项目，希望release后，所有的资源引用能替换为相对路径。
安装zoo后，我做了一个demo测试，但是releas后的路径并不符合预期。
demo结构：
/demo/index.html, 在index.htm里引用 app.js,   "js/app.js"
/demo/js/app.js

release后，
/output/index.html,  在index.html里的app.js 引用变成了 “../js/app.js",  预期的路径应该是”js/app.js"
/output/js/app.js

@xwenliang, 请问是我配置的问题，还是 zoo并不是设计做这个的。

附上配置：

``` javascript
//发布为相对路径
fis.config.set('roadmap.relative', true);

//部署配置
fis.config.set('roadmap.path', [

    {
        reg:/.*\.(?:js|sass|css|png|jpg|gif|html)/i,
        release: '$&'
    },

    //任何其它文件不发布
    {
        reg: /\w+.(?:json|cmd)/i,
        release: false
    }
]);


//使用fis release --dest local来使用这个配置
fis.config.merge({
    deploy : {
        local : {
            to : '../output',
            exclude: /(?:\/_[^/]+\.\w+)|(?:\.(?:cmd|json))$/i
        }
    }
});
```

**Comment by xwenliang** [comment]
@Julienedies :
问题提的好啊，正好命中了一个bug
设计相对路径，就是为了解决某些特殊项目必须使用相对路径的问题，比如你提到的hybrid app
现在bug已经修复，将fis-zoo更新到v2.1.1就ok了

附上：[修复代码](https://github.com/xwenliang/zoo-kernel/commit/d45b194f785d825735d0ec4883a47077866cae20)

**Comment by luckymore** [comment]
**here you go :+1:**

**Comment by Julienedies** [comment]
@xwenliang ，非常感谢 ：)， it's good!.

话说我的运气不错，好不容易找到这个项目...

**Comment by xwenliang** [comment]
：）很高兴能帮到你，有问题还请再次指正
